[package]
name = "article_scraper"
version = "0.1.0"
authors = ["Jan Lukas Gernert <jangernert@gmail.com>"]
edition = "2018"

[dependencies]
failure = "0.1"
libxml = { git = "https://github.com/KWARC/rust-libxml.git" }
reqwest = { version = "0.10.0-alpha.1", features = ["json"] }
tokio = { version = "=0.2.0-alpha.6" }
url = "2.1"
regex = "1.3"
encoding_rs = "0.8"
chrono = "0.4"
htmlescape = "0.3"
base64 = "0.11"
image = "0.22"
log = "0.4"