[package]
name = "article_scraper"
version = "0.1.0"
authors = ["Jan Lukas Gernert <jangernert@gmail.com>"]

[dependencies]
failure = "0.1.2"
libxml = "0.2.2"
reqwest = "0.8.7"
url = "1.7.1"
regex = "1.0.2"
encoding_rs = "0.8.4"
chrono = "0.4.5"
htmlescape = "0.3.1"
base64 = "0.9.2"
image = "0.19.0"
log = "0.4.3"
mime_guess = "1.8.6"
