[package]
name = "article_scraper"
version = "0.1.0"
authors = ["Jan Lukas Gernert <jangernert@gmail.com>"]

[dependencies]
failure = "0.1"
libxml = "0.2"
reqwest = "0.8"
url = "1.7"
regex = "1.0"
encoding_rs = "0.8"
chrono = "0.4"
base64 = "0.9"
image = "0.19"
log = "0.4"
mime_guess = "1.8"
