[package]
name = "article_scraper"
version = "1.0.0"
authors = ["Jan Lukas Gernert <jangernert@gmail.com>"]
edition = "2018"

[dependencies]
failure = "0.1"
libxml = "0.2"
reqwest = { version = "0.10", features = ["json", "native-tls"] }
tokio = { version = "=0.2", features = ["macros"] }
url = "2.1"
regex = "1.3"
encoding_rs = "0.8"
chrono = "0.4"
htmlescape = "0.3"
base64 = "0.12"
image = "0.23"
log = "0.4"